version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

parameters:
  run-auto-workflows:
    description: |
      Boolean that controls when an workflow would run.
      It is used to gate which workflows should run when github events occur.
      This parameter is used by automation to determine if a workflow will run within a pipeline.
    default: true
    type: boolean
  run-dependabot-automerge:
    description: >
      Boolean that controls when dependabot-automerge will run

      This parameter is used by an scheduled trigger to determine if the
      dependabot-automerge workflow will run.
    type: boolean
  run-test-ts-update:
    description: >
      Boolean that controls when test-ts-update will run

      This parameter is used by an scheduled trigger to determine if the
      test-ts-update workflow will run.
    type: boolean
    default: false
  run-just-nuts:
    description: |
      Boolean that controls when the just-nuts will run.
      Default value is false and this parameter is used by automation to determine if
      the just-nuts workflow will run.
    default: false
    type: boolean
  sfdx_version:
    description: |
      By default, the latest version of the standalone CLI will be installed.
      To install via npm, supply a version tag such as "latest" or "6".
    default: ''
    type: string
  repo_tag:
    description: The tag of the module repo to checkout, '' defaults to branch/PR
    default: ''
    type: string

workflows:
  test-and-release:
    when: << pipeline.parameters.run-auto-workflows >>
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
            exclude:
              - os: windows
                node_version: lts
              - os: windows
                node_version: maintenance
      - release-management/test-nut:
          matrix:
            parameters:
              os:
                - linux
                - windows
              sfdx_version:
                - latest
              node_version:
                - latest
          requires:
            - release-management/test-package
      - release-management/release-package:
          sign: true
          github-release: true
          requires:
            - release-management/test-package
          filters:
            branches:
              only: main
  test-ts-update:
    when: << pipeline.parameters.run-test-ts-update >>
    jobs:
      - release-management/test-ts-update
  dependabot-automerge:
    when: << pipeline.parameters.run-dependabot-automerge >>
    jobs:
      - release-management/dependabot-automerge
