name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  nuts:
    concurrency:
      group: ${{ github.repository }}
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@sm/parameterized-nut-secrets
    secrets:
      SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ secrets.SF_CHANGE_CASE_SFDX_AUTH_URL }}
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL }}
      SF_CHANGE_CASE_TEMPLATE_ID: ${{ secrets.SF_CHANGE_CASE_TEMPLATE_ID }}
      SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ secrets.SF_CHANGE_CASE_CONFIGURATION_ITEM }}
    with:
      # these are never meant to run on windows
      # only static-ip runners can talk to the org
      os: static-ip-ubuntu-runners
