name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  nuts:
    concurrency:
      group: ${{ github.repository }}
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@sm/parameterized-nut-secrets
    secrets:
      SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ secrets.SF_CHANGE_CASE_SFDX_AUTH_URL }}
    strategy:
      matrix:
        # these are never meant to run on windows
        os: [ubuntu-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
